travis:
  secure:
    BINSTAR_TOKEN: f/8HhqEVBbsrIte96Xh7zuqGMiewP3Nohb8EvnEpjaMQsBkj2LnTyHhtitsHasWEahu7nNYT9w7r3UKRRUqYmU43EHWpVSLYSuiBNUmTtUTcqYh0W2A5ajPCCpVnlvY0KT2zrJUv03tvh2Q3rW0jf0N9dxAjJ6JKu9jHdd79vaFTHW6so12KklsB0incMqC9NxGu9lrFotkzhCGvB0CvohnaN/44hCysHBq4w5NnN7f6Ua0y4YhBRUe7Cb5KKOlonFE2pYxYBMlA29LKDmEFhxboKd2XxpW8F+I1T4W9qK8kR6OOkj3j/feSShur9psapFmmnBm52cL0dVpIkYM/FMA4BtUauwtEbBfOhjZ2IRoJK+BIyU2wSZ4U1mRecv+5raqt5zmxMcjunRLdwinLWQwOglL6llG78xn9XHI1OzwG0KRanMqpVLle4AWW5urZrvrdn+WKSYFKRe7z4N4zoNpzwASC8tT1jby/r1duWxcZMFxnraQoO2DPSgVbTK4VOWOd3A3itiEfF3LTAz/oqEh0wxEjLxHtYPG6eyMzQRufIN9p/Y0IISxMjn3DcrBGncaNkDEcI/UiIpDdW2AWGx3I65UyTlKkvfc/CiuaImu6n3GIY1lF85wkD5dI/b79vDl/LoXKngRY1mnp3nDHGA8hbeu/snbhPVpQxvIWx08=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
